### ISSUE TITLE
零基础肯定可以呀，别慌，专注于技术就好啦

### ISSUE THREAD

**Issue by AB-pixel-pixel** [Leo204-LKY/LiKeyu_RecruitTask#1]
其实我们还有一些基础任务还没出，现在的都是进阶任务。看起来有点难也正常。别慌，慢慢把知识体系啃透就好了。

**Comment by Leo204-LKY** [comment]
好的好的，非常感谢鼓励
（自己创的 Repo 居然没 Watch 上，今天才看到orz
